### ISSUE TITLE
viera-pair error

### ISSUE THREAD

**Issue by daciand** [AntonioMeireles/homebridge-vieramatic#1]
Hi,
First of all, thanks a lot for implementing this module! I really need it!
But, for the moment I have the following error while executing the step 3 from your installation procedure:

```
pi@raspberrypi:~ $ sudo viera-pair 192.168.0.153
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '@lib/cli'
Require stack:
- /usr/lib/node_modules/homebridge-vieramatic/bin/pair.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-vieramatic/bin/pair.js:11:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/node_modules/homebridge-vieramatic/bin/pair.js' ]
}
```

Therefore I have no idea how to continue. Thank you!

L.E. I forgot to mention that I have a FZ800 series TV (55") and that I already did the TV setup that you mentioned on the module page.

**Comment by daciand** [comment]
Launching `viera-pair` with or without `sudo` produces the same effect.

**Comment by daciand** [comment]
fixed by replacing `(require('@lib/cli')` with `(require('../lib/cli')`.

**Comment by AntonioMeireles** [comment]
@daciand 

thanks and sorry for the typo! fixed in latest published version. 

have a great weekend!
