### ISSUE TITLE
Works for a day then I get this in the logs

### ISSUE THREAD

**Issue by Peterjohnwood** [AntonioMeireles/homebridge-vieramatic#15]
![B80560FD-B263-444B-9FFE-07EEC9CE3614](https://user-images.githubusercontent.com/56692030/79390352-72a50d80-7f67-11ea-9d50-9079103b2eb1.jpeg)

It stops working.... Should I re install?

**Comment by AntonioMeireles** [comment]
humm... can you paste to this issue the full error log (lines bellow that ones) please ? This is the closest i'm getting to understand why that happens for some people **but** i need to spot what the trigger/context was ...

thanks again for your patience!

**Comment by Peterjohnwood** [comment]
I'll paste the full log from when i restarted homebridge last night, the the restart this morning.....looks like 400 error. Could this be anything to do authentication tokens, the freuency is about every 1-2 hours....

[4/15/2020, 22:22:54] [Config] Homebridge restart request received
[4/15/2020, 22:22:55] [Config] No restart command defined, killing process...
[4/15/2020, 22:22:55] [HB Supervisor] Stopping services...
[4/15/2020, 22:22:55] Got SIGTERM, shutting down Homebridge...
[4/15/2020, 22:23:00] [Config] Failed to refresh characteristics for BADBOY Volume: socket hang up
[4/15/2020, 22:23:00] [Config] Failed to refresh characteristics for BADBOY Volume: socket hang up
[4/15/2020, 22:23:00] [Config] Failed to refresh characteristics for BADBOY Volume: socket hang up
[4/15/2020, 22:23:00] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/15/2020, 22:23:04] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[4/15/2020, 22:23:04] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[4/15/2020, 22:23:04] [HB Supervisor] Starting Homebridge with extra flags: -I -R
[4/15/2020, 22:23:04] [HB Supervisor] Started Homebridge with PID: 28989
[4/15/2020, 22:23:06] Loaded config.json with 7 accessories and 4 platforms.
[4/15/2020, 22:23:06] ---
[4/15/2020, 22:23:09] [Config] Homebridge Config UI X v4.15.1 is listening on :: port 8581
[4/15/2020, 22:23:08] Loaded plugin: homebridge-camera-ffmpeg
[4/15/2020, 22:23:08] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[4/15/2020, 22:23:08] ---
[4/15/2020, 22:23:09] Loaded plugin: homebridge-config-ui-x
[4/15/2020, 22:23:09] Registering platform 'homebridge-config-ui-x.config'
[4/15/2020, 22:23:09] ---
[4/15/2020, 22:23:10] Loaded plugin: homebridge-ring
[4/15/2020, 22:23:10] Registering platform 'homebridge-ring.Ring'
[4/15/2020, 22:23:10] ---
[4/15/2020, 22:23:11] Loaded plugin: homebridge-sky-q
[4/15/2020, 22:23:11] Registering accessory 'homebridge-sky-q.SkyQ'
[4/15/2020, 22:23:11] ---
[4/15/2020, 22:23:14] Loaded plugin: homebridge-vieramatic
homebridge API version: 2.4
homebridge-vieramatic version: 0.9.8
- Documentation: https://github.com/AntonioMeireles/homebridge-vieramatic#README
- Bugs and feedback: https://github.com/AntonioMeireles/homebridge-vieramatic/issues

[4/15/2020, 22:23:14] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[4/15/2020, 22:23:14] ---
[4/15/2020, 22:23:14] Loading 4 platforms...
[4/15/2020, 22:23:14] [Config] Initializing config platform...
[4/15/2020, 22:23:14] [Config] Running in Service Mode
[4/15/2020, 22:23:14] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[4/15/2020, 22:23:14] [PanasonicVieraTV] Vieramatic Init
[4/15/2020, 22:23:14] [Ring] Initializing Ring platform...
[4/15/2020, 22:23:14] [Camera ffmpeg] Initializing Camera-ffmpeg platform...
[4/15/2020, 22:23:14] Loading 7 accessories...
[4/15/2020, 22:23:14] [Sky Q Power] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [Record] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [TV Guide] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [UHD] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [Sky News] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [Sky Sports] Initializing SkyQ accessory...
[4/15/2020, 22:23:14] [Cartoons] Initializing SkyQ accessory...
Setup Payload:
X-HM://00244LEQAB6GB
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ***-**-*** │     
    └────────────┘     
                       
[4/15/2020, 22:23:14] Homebridge is running on port 51035.
[4/15/2020, 22:23:14] Drive is running on port 43189.
[4/15/2020, 22:23:14] Please add [Drive] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:14] Down the side is running on port 44277.
[4/15/2020, 22:23:14] Please add [Down the side] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:14] Sliding Doors is running on port 45005.
[4/15/2020, 22:23:14] Please add [Sliding Doors] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:14] Porch is running on port 41173.
[4/15/2020, 22:23:14] Please add [Porch] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:14] Garage is running on port 40059.
[4/15/2020, 22:23:14] Please add [Garage] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:14] Roof is running on port 41505.
[4/15/2020, 22:23:14] Please add [Roof] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:15] [PanasonicVieraTV] found a Panasonic VIErA TV (TX-65FZ950B) at 192.168.*.** (requires crypto for comunication).

[4/15/2020, 22:23:14] [Ring] Request for machine id timed out.  Falling back to random session id
[4/15/2020, 22:23:15] [PanasonicVieraTV] DidFinishLaunching
[4/15/2020, 22:23:15] BADBOY is running on port 33613.
[4/15/2020, 22:23:15] Please add [BADBOY] manually in Home app. Setup Code: ***********
[4/15/2020, 22:23:21] [Ring] Configuring 1 cameras and 1 devices for location "Sutton" - locationId: ***********
[4/15/2020, 22:23:21] [Ring] Adding new accessory doorbell_v4 Front Door
[4/15/2020, 22:23:21] Front Door is running on port 36321.
[4/15/2020, 22:23:21] Please add [Front Door] manually in Home app. Setup Code: ***********
[4/15/2020, 22:35:56] [Sky Q Power] Sky Q Power is on :-)
**[4/15/2020, 23:24:34] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/15/2020, 23:24:34] [Sky Q Power] Sky Q Power is in standby :-(
[4/16/2020, 00:57:43] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
**[4/16/2020, 01:23:37] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 01:23:37] [Sky Q Power] Sky Q Power is in standby :-(
[4/16/2020, 01:32:27] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
**[4/16/2020, 03:23:27] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 03:23:45] [Sky Q Power] Unable to determine power state 3
[4/16/2020, 03:23:45] [Sky Q Power] Perhaps looking at this error will help you figure out whyRequestError: Error: connect EHOSTUNREACH 192.168.1.176:9006
**[4/16/2020, 03:25:56] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 03:25:59] [Sky Q Power] Unable to determine power state 3
[4/16/2020, 03:25:59] [Sky Q Power] Perhaps looking at this error will help you figure out whyRequestError: Error: connect EHOSTUNREACH 192.168.1.176:9006
**[4/16/2020, 05:25:31] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 05:25:34] [Sky Q Power] Unable to determine power state 3
[4/16/2020, 05:25:34] [Sky Q Power] Perhaps looking at this error will help you figure out whyRequestError: Error: connect EHOSTUNREACH 192.168.1.176:9006
[4/16/2020, 05:46:14] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
**[4/16/2020, 06:32:59] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 06:32:59] [Sky Q Power] Sky Q Power is in standby :-(
[4/16/2020, 06:53:31] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[4/16/2020, 07:13:33] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[4/16/2020, 07:21:49] [Sky Q Power] Sky Q Power is in standby :-(
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Roof at 480:270
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Garage at 480:270
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Down the side at 480:270
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Sliding Doors at 480:270
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Drive at 480:270
[4/16/2020, 07:21:53] [Camera ffmpeg] Snapshot from Porch at 480:270
[4/16/2020, 07:21:53] [Ring] Snapshot for Front Door Requested
[4/16/2020, 07:21:58] [Ring] Snapshot for Front Door Received (4.907s)
[4/16/2020, 07:22:08] [Camera ffmpeg] Snapshot from Roof at 480:270
[4/16/2020, 07:22:09] [Ring] Snapshot for Front Door Requested
[4/16/2020, 07:22:09] [Ring] Snapshot for Front Door is still within its life time (11.792s old)
[4/16/2020, 07:22:09] [Ring] Snapshot for Front Door Received (0.002s)
**[4/16/2020, 07:31:04] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 07:31:04] [Sky Q Power] Sky Q Power is in standby :-(
**[4/16/2020, 07:35:25] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 07:35:25] [Sky Q Power] Sky Q Power is in standby :-(
**[4/16/2020, 08:30:21] [PanasonicVieraTV] (getVolume) Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function]
}**
[4/16/2020, 08:30:21] [Sky Q Power] Sky Q Power is in standby :-(
[4/16/2020, 09:09:25] [Config] Homebridge restart request received

**Comment by AntonioMeireles** [comment]
**THANKS!**

to fill a few more blanks in the big picture ...

- can you get here the contents of `/var/lib/homebridge/accessories/cachedAccessories/vieramatic.json` please ? 
- Also, you have activated on your TV **`Networked Standby`** and **`Powered On by Apps`**, (per [here](https://github.com/AntonioMeireles/homebridge-vieramatic#tv-setup)), right ?
- Also, TV is connected to the LAN wirelessly or wired ?

we're going to sort this as we're even in similar time zones :-) 

Thanks again for your patience!

**Comment by Peterjohnwood** [comment]
@AntonioMeireles do you need the content of both the files, cached accessories and vieramatic.json?

Yes yes and wired for the last questions

**Comment by AntonioMeireles** [comment]
just the vieramatic.json plz

**Comment by Peterjohnwood** [comment]
ok, pasted below - vieramatic.json. If I restart homebridge...everything works perfectly......it just stops after a while. 

{"4D454930-0200-1000-8001-80C75564E47C":{"data":{"inputs":{"hdmi":[{"id":"1","name":"SkyQ","hiden":0},{"id":"2","name":"PS4","hiden":0},{"id":"3","name":"Firestick","hiden":0},{"id":"4","name":"AppleTv","hiden":0}],"applications":{"0":{"name":"Apps Market","id":"0387878700000102","hiden":1},"1":{"name":"Netflix","id":"0010000200000001","hiden":0},"2":{"name":"Freeview Play","id":"0387878700000145","hiden":1},"3":{"name":"VIERA Link","id":"0387878700000016","hiden":1},"4":{"name":"YouTube","id":"0070000200180001","hiden":0},"5":{"name":"Browser","id":"0077777700160002","hiden":1},"6":{"name":"Amazon Prime Video","id":"0010000100180001","hiden":0},"7":{"name":"AccuWeather.com","id":"0070000C00000001","hiden":1},"8":{"name":"Audio Link","id":"0387878700000141","hiden":1},"9":{"name":"Recorded TV","id":"0387878700000013","hiden":1},"10":{"name":"Multi Window","id":"0387878700000050","hiden":1},"11":{"name":"Notification Center","id":"0387878700000140","hiden":1},"12":{"name":"Calendar","id":"0387878700150020","hiden":1},"13":{"name":"Smart Speaker Settings","id":"0387878700000146","hiden":1},"14":{"name":"Cinema","id":"0020002400180001","hiden":1},"15":{"name":"BBC iPlayer","id":"0020000A00170010","hiden":1},"16":{"name":"Plex","id":"0076010507000001","hiden":1},"17":{"name":"BritBox UK","id":"0020013200000001","hiden":1}},"TUNER":{"hiden":0}},"specs":{"friendlyName":"BADBOY","modelName":"Panasonic VIErA","modelNumber":"TX-65FZ950B","manufacturer":"Panasonic","serialNumber":"4D454930-0200-1000-8001-80C75564E47C","requiresEncryption":true}}}}

**Comment by AntonioMeireles** [comment]
(sorry lag) OK, can you mail me please (address is in git commit logs) so that we can debug this offline ? (will then mail you a test/debug version (probably more :-) ) in order to sort this out ...)

have a great weekend.

**Comment by AntonioMeireles** [comment]
closing as I believe this become a non issue in later releases. Please reopen or open a new issue if ithere's still room for improvement :-)
