### ISSUE TITLE
Hoobs service crashes when adding to Home

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#23]
Hello, 

I have an issue when adding the Tv to the Home app.

When i do the Add accessory, capture the qr code and the Tv is discovered. When i select next, the Tv appears offline and I have this error on the logs : 

```
6/3/2020, 12:36:32 PM Plugin "homebridge-wol" installed.6/3/2020, 12:36:33 PM Got SIGINT, shutting down Bridge...6/3/2020, 12:36:38 PM Loaded plugin "homebridge-vieramatic".6/3/2020, 12:36:38 PM homebridge API version: 2.56/3/2020, 12:36:38 PM homebridge-vieramatic version: 0.9.126/3/2020, 12:36:38 PM - Documentation: https://github.com/AntonioMeireles/homebridge-vieramatic#README6/3/2020, 12:36:38 PM - Bugs and feedback: https://github.com/AntonioMeireles/homebridge-vieramatic/issues6/3/2020, 12:36:38 PM Loaded plugin "homebridge-wol".6/3/2020, 12:36:38 PM [PanasonicVieraTV] Vieramatic Init6/3/2020, 12:36:38 PM Bridge is running on port 51826.6/3/2020, 12:36:38 PM [PanasonicVieraTV] found a Panasonic VIErA TV (TX-65GZ2000E) at 192.168.1.10 (requires crypto for comunication).
6/3/2020, 12:36:38 PM [PanasonicVieraTV] DidFinishLaunching6/3/2020, 12:36:38 PM Galaxy-TV is running on port 50199.6/3/2020, 2:01:26 PM Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/src/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:11:19
    at Accessory.<anonymous> (/usr/src/hoobs/bridge/platform.js:57:13)
    at Accessory.emit (events.js:310:20)
    at Accessory.EventEmitter.emit (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Accessory._this._identificationRequest (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:147:23)
    at Identify.<anonymous> (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1079:23)
    at Identify.emit (events.js:310:20)
    at Identify.EventEmitter.emit (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Identify.Characteristic._this.setValue (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:356:23)
    at /usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:938:36
    at Array.forEach (<anonymous>:null:null)
    at Accessory._this._handleSetCharacteristics (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:806:18)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:718:23)
    at IncomingMessage.<anonymous> (/usr/src/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
6/3/2020, 2:01:26 PM Got SIGTERM, shutting down Bridge...
```

When i start the service and go next for the Scenes, it crashes again. 

If i restart the service afterward, it works good without issue. 

I'm on Hoobs 3.2.6, running on Synology Docker fresh installation.

Thanks a lot, take care

**Comment by AntonioMeireles** [comment]
@Seexelas

Hi, 

could you please attach here a full copy of your homebridge config ?

Thanks for your patience!

P.S. I envy you and your TV :-)  - Top of line OLED!

**Comment by Seexelas** [comment]
Hello Antonio,

Thanks for your answer, here is my full config.json.

https://www.dropbox.com/s/lg2pw66m8ducjb0/config.json?dl=0

I had the opportunity to buy it, you are right, it's a great tv !

Thanks again,

**Comment by AntonioMeireles** [comment]
closing. digging in the hoobs front continues in #14

**Comment by AntonioMeireles** [comment]
closing. digging in the hoobs front continues in #14
