### ISSUE TITLE
Issue adding a third HDMI port

### ISSUE THREAD

**Issue by stijndevries** [AntonioMeireles/homebridge-vieramatic#7]
First off, thank you so much for this! Really an amazing plugin. 
When I try to add a third HDMI port the following happens: 
```
[1/27/2020, 9:00:30 PM] Homebridge is running on port 51998.
found a Panasonic VIErA TV (TX-42AS650E) at 192.168.0.130.
[1/27/2020, 9:00:30 PM] [PanasonicVieraTV] An unexpected error happened while adding Viera TV (at '192.168.0.130') as an homebridge Accessory.
TypeError: Cannot read property 'hiden' of undefined
[1/27/2020, 9:00:30 PM] [PanasonicVieraTV] DidFinishLaunching
```

This is my config:
```
{
            "platform": "PanasonicVieraTV",
            "tvs": [
                {
                    "ipAddress": "192.168.0.130",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "TV"
                        },
                        {
                            "id": "2",
                            "name": "Spel"
                        },
                        {
                            "id": "3",
                            "name": "Apple TV"
                        }
                    ]
              }
        ]
 }
```

When I remove the third port it works fine.

**Comment by AntonioMeireles** [comment]
OK, right now, i'm [not](https://github.com/AntonioMeireles/homebridge-vieramatic/blob/master/lib/homebridge.coffee#L146) handling additions/modifications to App listing or HDMI inputs... will do my best to do it soonish :-) 

in the meantime - if you delete `accessories/vieramatic.json` under homebridge dir and restart homebridge you should be able to get all inputs being consumed .

All the best and **THANKS** for your kind words :-)

**Comment by AntonioMeireles** [comment]
@stijndevries, @chrismaurer

could you test latest version, please, and report back ? should get this implemented.

(FWIW there's an annoying 'feature' in Home.app both in latest ios and macOS, where you may have to exit it and go back to it to get inputs showing correctly immediatly after changing inputs / restarting homebridge) 

All the best!

**Comment by stijndevries** [comment]
Thanks for the quick response! After accidentally removing the TV from the Home app, I'm not able to get it back anymore. 
It shows up in the HomeBridge terminal as being found but I cannot see it when adding the TV manually in the home app. My other accessories are acting a little strange as well  today so it might just be a problem on my end...

**Comment by stijndevries** [comment]
It also adds a vieramatic.json file so it is connected to the TV, it just doesn't show up in the home app.
![image](https://user-images.githubusercontent.com/25649105/73393433-ebd38380-42db-11ea-86cc-3d1ad951cff2.png)

**Comment by stijndevries** [comment]
Is it possible that this is happening because the Setup Code for the TV is the same as the setup code of Homebridge, os is that by design?

**Comment by AntonioMeireles** [comment]
unrelated. TV is setup as an external accessory (settings stored  out of homebridge in `vieramatic.json`) but setup pin shared with homebridge. can you call/restart  homebridge with `DEBUG=*` and get me back the logs to check if there's some clue there ?  (at sight this looks unrelated with my latest iterations but ...) 

Thanks in advance

**Comment by stijndevries** [comment]
Yes, this is on my side, already tried with the previous version. 
This is the log that I get, an EADDRINUSE error:
`DEBUG=* homebridge -D
[1/29/2020, 9:49:40 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/29/2020, 9:49:40 PM] ---
[1/29/2020, 9:49:40 PM] Loaded plugin: homebridge-config-ui-x
[1/29/2020, 9:49:40 PM] Registering platform 'homebridge-config-ui-x.config'
[1/29/2020, 9:49:40 PM] ---
[1/29/2020, 9:49:40 PM] Plugin /usr/local/lib/node_modules/homebridge-fritz-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v12.13.1. You may need to upgrade your installation of Node.
[1/29/2020, 9:49:40 PM] Loaded plugin: homebridge-fritz-platform
[1/29/2020, 9:49:41 PM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[1/29/2020, 9:49:41 PM] ---
[1/29/2020, 9:49:41 PM] Loaded plugin: homebridge-sonos
[1/29/2020, 9:49:41 PM] Registering accessory 'homebridge-sonos.Sonos'
[1/29/2020, 9:49:41 PM] ---
[1/29/2020, 9:49:41 PM] Loaded plugin: homebridge-sonytvpower
[1/29/2020, 9:49:41 PM] Registering accessory 'homebridge-sonytvpower.SonyTV'
[1/29/2020, 9:49:41 PM] ---
[1/29/2020, 9:49:42 PM] Loaded plugin: homebridge-vieramatic
homebridge API version: 2.4
[1/29/2020, 9:49:42 PM] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[1/29/2020, 9:49:42 PM] ---
[1/29/2020, 9:49:42 PM] Loaded plugin: homebridge-wol
[1/29/2020, 9:49:42 PM] Registering accessory 'homebridge-wol.NetworkDevice'
[1/29/2020, 9:49:42 PM] ---
[1/29/2020, 9:49:42 PM] Loading 1 platforms...
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] Vieramatic Init
[1/29/2020, 9:49:42 PM] Loading 1 accessories...
[1/29/2020, 9:49:42 PM] [Sonos Speaker] Initializing Sonos accessory...
Load homebridge-fritz-platform.FritzPlatform
Setup Payload:
X-HM://0023YPKYY0EJM
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 298-60-970 │     
    └────────────┘     
                       
[1/29/2020, 9:49:42 PM] Error: listen EADDRINUSE: address already in use :::51496
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

[1/29/2020, 9:49:42 PM] Got SIGTERM, shutting down Homebridge...
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] 192.168.0.130
  follow-redirects options {
  protocol: 'http:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/nrc/ddd.xml',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'User-Agent': 'axios/0.19.2'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: '192.168.0.130',
  port: '55000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function],
      request: [Function]
    }
  }
} +0ms
found a Panasonic VIErA TV (TX-42AS650E) at 192.168.0.130.

  follow-redirects options {
  protocol: 'http:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/nrc/sdd_0.xml',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'User-Agent': 'axios/0.19.2'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: '192.168.0.130',
  port: '55000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function],
      request: [Function]
    }
  }
} +18ms
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] Viera {
  isReachable: [Function: bound isReachable],
  ipAddress: '192.168.0.130',
  port: 55000,
  baseURL: 'http://192.168.0.130:55000',
  specs: {
    friendlyName: 'Viera',
    modelName: 'Panasonic VIErA',
    modelNumber: 'TX-42AS650E',
    manufacturer: 'Panasonic',
    serialNumber: '4D454930-0200-1000-8001-20C6EBA2563B'
  }
}
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] Restoring 'Viera'.
  follow-redirects options {
  protocol: 'http:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/nrc/control_0',
  method: 'POST',
  headers: {
    Accept: 'text/xml',
    'Content-Type': 'text/xml; charset="utf-8"',
    Host: '192.168.0.130:55000',
    SOAPACTION: '"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList"',
    'Cache-Control': 'no-cache',
    Pragma: 'no-cache',
    'User-Agent': 'axios/0.19.2',
    'Content-Length': 292
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: '192.168.0.130',
  port: '55000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function],
      request: [Function]
    }
  }
} +26ms
[1/29/2020, 9:49:42 PM] [PanasonicVieraTV] DidFinishLaunching
  EventedHTTPServer Server listening on port 49297 +0ms
[1/29/2020, 9:49:42 PM] Viera is running on port 49297.
[1/29/2020, 9:49:42 PM] Please add [Viera] manually in Home app. Setup Code: 298-60-970
[1/29/2020, 9:49:42 PM] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:210:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage (dgram.js:861:8)

[1/29/2020, 9:49:43 PM] [Sonos Speaker] Found sonos device at 192.168.0.174
[1/29/2020, 9:49:43 PM] [Sonos Speaker] Found a playable device at 192.168.0.174 for room 'Dining Room'`

**Comment by stijndevries** [comment]
I fixed it by completely resetting home bridge. Adding custom HDMI ports works for me, thank you very much! One more thing, would it be possible to remove the volume switch or change it to a fan accessory because when I say "set the lights to 100%" the volume of the TV will change to 100%....

**Comment by AntonioMeireles** [comment]
> One more thing, would it be possible to remove the volume switch or change it to a fan accessory because when I say "set the lights to 100%" the volume of the TV will change to 100%....

@stijndevries sure it is. will do soonish :-)

**Comment by AntonioMeireles** [comment]
@stijndevries, 

just give a try to 0.5.15  please . speaker is now a Fan.

**Comment by AntonioMeireles** [comment]
closing as, AFAICT, this is now **really** fixed. please reopen if it is not.

**Comment by stijndevries** [comment]
> @stijndevries,
> 
> just give a try to 0.5.15 please . speaker is now a Fan.

With HOOBS I'm able to use my RPi again (I broke the HDMI port and HOOBS is headless) Thanks for fixing this and this great plugin!
