### ISSUE TITLE
TypeError: Cannot read property 'hidden' of undefined

### ISSUE THREAD

**Issue by chrismaurer** [AntonioMeireles/homebridge-vieramatic#75]
**Homebridge terminating due to Vieramatic TypeError exception**

```
[3/22/2021, 2:04:02 PM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-49FX750) at '192.168.21.123' (requires crypto for comunication).

TypeError: Cannot read property 'hidden' of undefined
    at visibility (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:394:33)
    at VieramaticPlatformAccessory.configureInputSource (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:436:20)
    at new VieramaticPlatformAccessory (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:311:10)
    at VieramaticPlatform.deviceSetup (/usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:217:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:63:23
TypeError: Cannot read property 'hidden' of undefined
    at visibility (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:394:33)
    at VieramaticPlatformAccessory.configureInputSource (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:436:20)
    at new VieramaticPlatformAccessory (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:311:10)
    at VieramaticPlatform.deviceSetup (/usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:217:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:63:23
[3/22/2021, 2:04:03 PM] Got SIGTERM, shutting down Homebridge...
```
...
disabling vieramatic
...
```
[3/22/2021, 2:04:18 PM] ---
[3/22/2021, 2:04:19 PM] Disabled plugin: homebridge-vieramatic@2.0.26
[3/22/2021, 2:04:19 PM] ---
[3/22/2021, 2:04:19 PM] Ignoring config for the platform "PanasonicVieraTV" in your config.json as the plugin "homebridge-vieramatic" has been disabled.
[3/22/2021, 2:04:21 PM] Homebridge v1.3.2 (Homebridge) is running on port 51793.
```

Hello António!
It's been a long time! I've been happily running on version 0.5.15 for all this time (since the time of this issue: https://github.com/AntonioMeireles/homebridge-vieramatic/issues/3)
I decided to try upgrading to 3.1.8 and had a bit of an issue. I thought I'd give downgrading to 2.0.26 a go, but had the same issue as I've shown above. Just to be on the safe side I completed the pairing process over again.
I didn't see the same issue reported in other Issues so I've opened this new one.
If you're able to look into this that would be much appreciated.

Kudos on adding the "Settings" configuration UI and other new features. It's looking good and I'm delighted to see that you have continued working so hard on this and supporting so many users! Very nicely done!

**Comment by AntonioMeireles** [comment]
@chrismaurer 

hi again (&& huge thanks for the kind words from literally the other side of the world!) 

on disk saved settings format changed a bit (ironically to fix a spelling typo) a while ago  and not all migration corner cases were covered it seems :( . 

just remove the `accessories/vieramatic.json` (in the homebridge dir) and then restart homebridge. (if i'm right) it should get all smooth again.

All the best, 

António

**Comment by chrismaurer** [comment]
Hi António,

Thanks for the quick response. Yes indeed that worked perfectly. The latest version is working really well. Thanks!

**Comment by AntonioMeireles** [comment]
> Hi António,
> 
> Thanks for the quick response. Yes indeed that worked perfectly. The latest version is working really well. Thanks!

great to hear! 

will close. feel free to bug me again if need arises! 

All the best, 

António
