### ISSUE TITLE
Tv shows as No Response. 

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#83]
Hi Antonio, 

Since a few time now, earch time I reboot my Homebridge instance (mostly to update plugins). Each time if the tv is in standby mode, it will show as No Reponse in Home. I have to start the Tv, reboot the instance and it works. 

The error message tells me that the Initial Setup can not be done in stand by mode. I try by doing a first setup, with the pair code on my Tv, it works and after that, same issue. 

I also received this error : 

[9/16/2021, 5:00:31 PM] [PanasonicVieraTV] unable to fetch Apps list from the TV:

 The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (249)

Here is my config : 

        {
            "tvs": [
                {
                    "customVolumeSlider": false,
                    "encKey": "XXXXXXXXXXXXXXXXX",
                    "ipAddress": "192.168.1.10",
                    "disabledAppSupport": false,
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "HDMI - 1"
                        },
                        {
                            "name": "HDMI - 2",
                            "id": "2"
                        },
                        {
                            "name": "HDMI - 3",
                            "id": "3"
                        },
                        {
                            "name": "HDMI - 4",
                            "id": "4"
                        }
                    ],
                    "appId": "AeRrvQARMlszCw==",
                    "friendlyName": "Galaxy - Tv"
                }
            ],
            "platform": "PanasonicVieraTV"
        },

Thanks for the help,

Best regards,

Alexis

**Comment by AntonioMeireles** [comment]
@Seexelas 

Hi! 

two quick questions ...

- a)  are... 
    - **Powered On by Apps**
    -  **Networked Standby**
    
   both activated in `Menu -> Network -> TV Remote App Settings` on your TV 
-  b) could you please provide full logs for wider context ? (also, what eaxct model do you have) ?  
  
  
  Thanks in advance!

**Comment by AntonioMeireles** [comment]
@Seexelas 

by chance has this started happening **JUST** after Panasonic's  very latest firmware update ? (the one that added Disney+ support ?)

**Comment by Seexelas** [comment]
Hi Antonio,

Thanks for the quick answer. 

No I was on the firwmare just before 3.222, I just did the update right now (I didn't know that there was a new firmware, Tv didn't prompt anything). I have a Panasonic TX-65GZ2000. 

a) are...

Powered On by Apps
Networked Standby

Yes both are. 

I did a fresh setup for the Tv plugin, I'll let you know as soon as I have the error again. 

Thanks

**Comment by AntonioMeireles** [comment]
@Seexelas 

Something has changed on TV's  firmware in latest iterations (for me was just yesterday, when i updated my GX800 to latest...). Sometimes, but not always, we're failing to properly decrypt TV's answers to our requests. It's not clear, to me, yet why (as it is new behaviour and doesn't seem to be deterministic - at least in my set). 

This error...
> `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (249)`
... shouldn't just happen (and afaict, it never did before)

So, thanks for reporting. Digging into it.   

All the best, 

António

P.S. I envy your TV set :-)

**Comment by AntonioMeireles** [comment]
@Seexelas 

please install `homebridge-vieramatic@3.1.23-beta.1` that i've just published (`npm i homebridge-vieramatic@3.1.23-beta.1`as it is tagged as beta) and confirm that both  your issues just had gone away and that no new ones arise. 

Thanks in advance! and a  great weekend!

**Comment by Seexelas** [comment]
Hi Antonio, 

It is installed, I get this error in the logs : 

[9/17/2021, 3:29:04 PM] No plugin was found for the platform "PanasonicVieraTV" in your config.json. Please make sure the corresponding plugin is installed correctly.

I did nothing special except going in terminal and type : npm i homebridge-vieramatic@3.1.23-beta.1

I rebooted my instance and got this error. 

Thanks for the help, 

Best regards, great week end to you too.

**Comment by Seexelas** [comment]
Here is the debug log : 

[9/17/2021, 3:37:43 PM] ====================
[9/17/2021, 3:37:43 PM] ERROR LOADING PLUGIN homebridge-vieramatic:
[9/17/2021, 3:37:44 PM] Error: Cannot find module 'fast-xml-parser'
Require stack:
- /homebridge/node_modules/homebridge-vieramatic/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-vieramatic/src/viera.ts:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[9/17/2021, 3:37:44 PM] ====================

**Comment by AntonioMeireles** [comment]
try please  -  `npm i homebridge-vieramatic@3.1.23-beta.2` that i just got pushed. 
 (**beta.1** had a typo - `fast-xml-parser` got unset as a runtime dep.)

**Comment by Seexelas** [comment]
Great thanks, it's working better. 

Now it's doing the same as before : 

[9/17/2021, 4:17:55 PM] [PanasonicVieraTV] Initializing 'Galaxy - Tv' first time ever.
[9/17/2021, 4:17:55 PM] [PanasonicVieraTV] Unable to finish initial setup of Galaxy - Tv.

In debug mode, I only get this two lines. 

I will try doing the whole setup again.

**Comment by AntonioMeireles** [comment]
TV is UP (powered on) ?
if no expected (just turn it on, and try again), if yes... can you paste contents of `accessories/vieramatic.json` (it's inside your homebridge config dir), please ?

**Comment by Seexelas** [comment]
Tv is on stand by (orange light). 

If I turn on the Tv, It's working again (but I have to reboot the instance). 

For the vieramatic.json... It only has this  : {}

**Comment by AntonioMeireles** [comment]
OK. when you reboot the instance the data on the fs is not persistent across reboots ? 
for context - channel list only has to be there (and be sucessfully fetched) on initial setup as in subsequent ones if it fails previous ones are on disk already. to fetch channels TV must really be turned ON and not just in standBy. Panasonic 'feature'.

**Comment by AntonioMeireles** [comment]
@Seexelas 

new version out (`homebridge-vieramatic@3.1.23-beta.3`). it now gets TV' built in apps properly synced to ones exposed to HomeKit. (previously apps were added at plugins' (first) initialization and not verified / checked anymore). 

Can you confirm that everything is now working as expected now on your side ? so that i could push this to everybody ? 

Thanks in advance and a great weeked!

**Comment by Seexelas** [comment]
Hi Antonio,

I installed it, Tv was on, so no error on instance reboot.

After I put the Tv in stand by, rebooted the instance and : 

[9/18/2021, 11:06:20 PM] [PanasonicVieraTV] Initializing 'Galaxy - Tv' first time ever.
[9/18/2021, 11:06:20 PM] [PanasonicVieraTV] Unable to finish initial setup of Galaxy - Tv.

 Please make sure that this TV is powered ON and NOT in stand-by.

Again this error and in Home Kit, the Tv appears in No reponse. 

I had also this warning during the plugin install (my NPM version was updated yesterday) : 

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...

**Comment by AntonioMeireles** [comment]
@Seexelas 

either i'm missing something or something odd going on - can you tell me more about how you have setup your homebridge instance ? [host/os/arch/node version/etc]

here's what i expect it should happen ... 
- first time: 
   - REQUIRED that TV is ON
   - when you instantiate homebridge you get the ` Initializing 'Galaxy - Tv' first time ever.`
     (this will create a fully populated `accessories/vieramatic.json` inside your homebridge conf dir)
- after that ...
   - you should be able to restart homebridge instance at will (assuming data persistence across restarts) and the TV is not required to be ON, can be in standby (as if it is cached data from previous runs (`accessories/vieramatic.json`) is consumed).   
   
   
Thanks once again for your patience!

**Comment by Seexelas** [comment]
Hi Antonio,

My Homebridge is ran into a Docker on my Synology DS916+ (DSM 7.0)

Docker is version 20.10,3-1233
Alpine Linux (3.12.8)
Node.js Version	v14.17.6
Npm Version | v7.24.0
Homebridge 1.3.4

Could you tell me what to be expected into vieramatic.json ? Mine is still : {} (but the modified date is changed , last time this morning). 

Data should be persistant has it my only plugin which is doing that when I restard. It's like the first setup is never complete for Homebridge.

First time setup is done with Tv on, and nothing goes wrong. 

It's only when I reboot the instance (docker is up since 19 days).

Thanks a lot for your help.

**Comment by AntonioMeireles** [comment]
on proper init `accessories/vieramatic.json` should have something along ...

```json
{
  "(...)": {
    "data": {
      "inputs": {
        "TUNER": {
          "hidden": 1
        },
        "applications": {
          "0": {
            "id": "0387878700000102",
            "name": "Apps Market"
          },
          "1": {
            "hidden": 1,
            "id": "0010000200000001",
            "name": "Netflix"
          },
          "2": {
            "hidden": 1,
            "id": "0070000200190001",
            "name": "YouTube"
          },
          "3": {
            "id": "0020002400180001",
            "name": "Cinema"
          },
          "4": {
            "hidden": 1,
            "id": "0387878700000016",
            "name": "VIERA Link"
          },
          "5": {
            "id": "0387878700000003",
            "name": "TV Guide"
          },
          "6": {
            "id": "007777770018A002",
            "name": "Browser"
          },
          "7": {
            "hidden": 1,
            "id": "0010000100190001",
            "name": "Amazon Prime Video"
          },
          "8": {
            "id": "0020000600000001",
            "name": "ARTE"
          },
          "9": {
            "id": "0020008500000001",
            "name": "TV5MONDE"
          },
          "10": {
            "id": "0020007100000001",
            "name": "Meteonews TV"
          },
          "11": {
            "id": "0010001800000001",
            "name": "TuneIn"
          },
          "12": {
            "id": "0076002307170001",
            "name": "Digital Concert Hall"
          },
          "13": {
            "id": "0387878700000146",
            "name": "Smart Speaker Settings"
          },
          "14": {
            "id": "0387878700000141",
            "name": "Audio Link"
          },
          "15": {
            "id": "0387878700000013",
            "name": "Recorded TV"
          },
          "16": {
            "id": "0387878700000050",
            "name": "Multi Window"
          },
          "17": {
            "id": "0387878700000140",
            "name": "Notification Center"
          },
          "18": {
            "id": "0387878700150020",
            "name": "Calendar"
          },
          "19": {
            "id": "0387878700000153",
            "name": "List Application"
          },
          "20": {
            "id": "0020007600000001",
            "name": "Deezer"
          },
          "21": {
            "id": "0070002900000002",
            "name": "Disney+"
          },
          "22": {
            "id": "0076010507000001",
            "name": "PLEX"
          }
        },
        "hdmi": [
          {
            "id": "1",
            "name": "VodafoneTV box"
          },
          {
            "id": "2",
            "name": "Apple TV 4k"
          }
        ]
      },
      "ipAddress": "192.168.1.80",
      "specs": {
        "friendlyName": "50GX830",
        "manufacturer": "Panasonic",
        "modelName": "Panasonic VIErA",
        "modelNumber": "TX-50GX800E",
        "requiresEncryption": true,
        "serialNumber": "(...)"
      }
    }
  }
}
```
('(...)' above replaces TV's Serial Number)). 

i don't get why it' s empty. it should only be empty on error.  **if** "First time setup is done with Tv on, and nothing goes wrong." **then** it should just be properly populated... digging. (i think this is now specific to your setup but not 100% sure yet)

**Comment by Seexelas** [comment]
I agree with you, I think it's from my side... But why... :D that's another question. 

I can try delete everything related to this plugin and try again. 

Is there somewhere on the Tv a place where is stored every paired devices ?

**Comment by AntonioMeireles** [comment]
not sure i understood your question.
what do you mean here by "paired devices" ?

**Comment by Seexelas** [comment]
When you pair Homebridge to the Tv's, it is stored somewhere on a Menu all the connections I made. 

Like on Netflix or Amazon, you can see of many devices connected to your account.

**Comment by Seexelas** [comment]
Hi Antonio,

So I have uninstalled the plugin, the configuration in the config.json, the vieramatic.json file, and the folder in node_modules for the plugin was deleted. 

I restarted the HB instance, the whole docker and installed the plugin back and did the configuration. 

The plugin works, I did the first setup, rebooted the instance, added the Tv to Homekit and it's communicating. I restarted the HB instance, and the the file vieramatic.json is still empty, and the log says : preparing for the first time setup.

So no chance by doing a clean up.

**Comment by AntonioMeireles** [comment]
@Seexelas 

sorry, i'm still lost. 
-  > The plugin works, I did the first setup, rebooted the instance, added the Tv to Homekit and it's communicating

   this means that `vieramatic.json` exists and  is fully populated.
- >  restarted the HB instance

    what do you mean above by 'restarted' vs 'rebooted' ?
    
could you please provide the dockerfile you are using plz. 

thanks again.

**Comment by Seexelas** [comment]
> * > The plugin works, I did the first setup, rebooted the instance, added the Tv to Homekit and it's communicating
>   
>   
>   this means that `vieramatic.json` exists and  is fully populated.

The file is there, still empty. I double checked. 

I saw that I have a persist folder with a file AccessoryInfo with the MacAdress of the TV with this : 

{"displayName":"Galaxy-Tv 4636","category":31,"pincode":"489-36-130","signSk":"23a16761447ea191283d06d64ba62435ee479ca07e0a667a83c92c2867bb32839886412385a31a6e651064d400a2038899b928d9dd82c0d8b10f1b5df100bb2e","signPk":"9886412385a31a6e651064d400a2038899b928d9dd82c0d8b10f1b5df100bb2e","pairedClients":{"0BE20822-78B7-4216-9D54-7B8C0005A8D1":"2be9782bd9b00f5f820592fa25816212ac5b06ec2e25b1a11d0c9c7da770d777","FBE3EBAA-924B-4344-B2AC-D048C1A798F8":"cabf796a4bea2c54aeccb674a5d2bc6e6622b8ae6782fecc0b52949ad56fd968"},"pairedClientsPermission":{"0BE20822-78B7-4216-9D54-7B8C0005A8D1":1,"FBE3EBAA-924B-4344-B2AC-D048C1A798F8":0},"configVersion":2,"configHash":"3c28f5a0b8adc9fee1d7e694c9c68014075b8f7a","setupID":"TNV4","lastFirmwareVersion":"0.9.4"},

And also a IdentifierCache with number in it, those are populated but the vieramatic.json is still empty. 

What I mean, is that I click on the Power Icon in Homebridge which does a restart of the instance, but today I also try a restart of the container. 

Here is the image : 

https://www.dropbox.com/s/o7l8xe5ynarixax/oznu-homebridge%28latest%29.syno.tar?dl=0

**Comment by AntonioMeireles** [comment]
@Seexelas 

i have no clue. it seems a docker/synology specific issue. per the [official docs](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology) at sight it seems you don'y have the   persistent volume properly set but not sure :/ sorry.

**Comment by Seexelas** [comment]
I will check for the persistent volume if there is any issue. 

Thanks for your help :)

**Comment by Seexelas** [comment]
Hi Antonio,

So I switch back to a fresh install on a Raspberry PI, I only added your plugin, I did the viera-pair and I get this error despite the config file is ok : 

[09/10/2021, 08:58:55] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TX-65GZ2000E) at '192.168.1.10' (requires crypto for communication).

[09/10/2021, 08:58:55] [PanasonicVieraTV] IGNORING '192.168.1.10' ('Panasonic VIErA') as no working credentials were supplied.

 Request failed with status code 500

-------------------------------------
           "tvs": [
                {
                    "friendlyName": "Galaxy-Tv",
                    "ipAddress": "192.168.1.10",
                    "encKey": "n4zJTnUSJLo/2m273zn+3w==\"",
                    "appId": "ATiVL7gn67YCjg==\"",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "HDMI - 1"
                        },
                        {
                            "id": "2",
                            "name": "HDMI - 2"
                        },
                        {
                            "id": "3",
                            "name": "HDMI - 3"
                        },
                        {
                            "id": "4",
                            "name": "HDMI - 4"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
---------------------------------------

Tv was on and connected during initial pair, 

Thanks for the help !

**Comment by Seexelas** [comment]
Also the vieramatic.json is in the same state as on docker... Empty except {}

**Comment by AntonioMeireles** [comment]
some quick questions:

a) what node version?
b) if you install previous plugin version (i released a new one yesterday)
things behave ?

António

**Comment by AntonioMeireles** [comment]
@Seexelas 

can you attach here please the full homebridge boot logs from the rPI ?

**Comment by Seexelas** [comment]
Here is the log (I hope it's the good one)
[log.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/7316081/log.txt)

**Comment by AntonioMeireles** [comment]
ok, by parts...

re: the homebridge log - it all looks sane. it detects the TV, in the homebridge config, and complains that no valid credentials were supplied. you then run the pairing helper. **BUT** then you need to edit the homebridge config again to add the supplied credentials (per the docs / `viera-pair` output and **AFTER** restart homebridge again to consume the newly added settings. the TV should then be properly detected. 

re: 
> the plugin does not match the current HDMI used on the Tv when the Tv is turned On or Homebridge instance is restarted

known limitation - There's nothing i can do regarding this **without help from Panasonic**. As far as i know historically the Panasonic's TV's firmware do not expose any way so that we can find what input/app/channel is actually being run on the TV - the best i could do is by default when turning TV give the user a chance of a known default (settable in the config) but no one requested that so far and it would be probabbly of limited use. 

All the best and a great weekend, 

António

**Comment by chiuch930** [comment]
Hi, @AntonioMeireles 
I have same issue with @Seexelas 
my environment is 
OS: CentOS8
Homebridge:1.3.5
Node.js:14.18.1

Config:
            "tvs": [
                {
                    "friendlyName": "TH-55HX750W",
                    "ipAddress": "172.16.0.175",
                    "encKey": "svn/9YXrgWBAib3mCLU0Eg==",
                    "appId": "AeRJAwAMKbv4gg==",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "HDMI1"
                        },
                        {
                            "id": "2",
                            "name": "HDMI2"
                        },
                        {
                            "id": "3",
                            "name": "HDMI3"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": true
                },
                {
                    "friendlyName": "TH-49GX750W",
                    "ipAddress": "172.16.0.247",
                    "encKey": "nZJ7NKFhVE5dQ3yDqtYBiw==",
                    "appId": "ARt9ZAAMKbv4gg==",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "HDMI1"
                        },
                        {
                            "id": "2",
                            "name": "HDMI2"
                        },
                        {
                            "id": "3",
                            "name": "HDMI3"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": true
                }
            ],
            "platform": "PanasonicVieraTV"

Log:
[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-55HX750W) at '172.16.0.175' (requires crypto for communication).

[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-49GX750W) at '172.16.0.247' (requires crypto for communication).

[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] Initializing 'TH-49GX750W' first time ever.
[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] Unable to finish initial setup of TH-49GX750W.

 Please make sure that this TV is powered ON and NOT in stand-by.
[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] Initializing 'TH-55HX750W' first time ever.
[10/19/2021, 7:29:33 PM] [PanasonicVieraTV] Unable to finish initial setup of TH-55HX750W.

 Please make sure that this TV is powered ON and NOT in stand-by.

**Comment by chiuch930** [comment]
it's message help to you
I have other device (roborock vacuum, mi fan, UniFi Protect)


[root@Homebridge accessories]# pwd
/var/lib/homebridge/accessories
[root@Homebridge accessories]# ls -al
total 192
drwxr-xr-x. 2 homebridge homebridge   122 Oct 20 20:00 .
drwxr-xr-x. 8 homebridge homebridge   242 Oct 19 19:28 ..
-rw-r--r--. 1 homebridge homebridge 90232 Oct 19 19:36 .cachedAccessories.bak
-rw-r--r--. 1 homebridge homebridge 90236 Oct 20 20:01 cachedAccessories
-rw-r--r--. 1 homebridge homebridge     3 Oct 18 16:31 cachedAccessories.0EC1A2CEEE85
-rw-r--r--. 1 homebridge homebridge     3 Oct 19 19:38 vieramatic.json
[root@Homebridge accessories]# cat vieramatic.json 
{}

**Comment by Seexelas** [comment]
Little update, I played with the plugin and configuration into Home, the vieramatic.json can be updated and written once it exists and rightly populated. 

It's the first setup and first filling which doesn't work
