### ISSUE TITLE
Spinning wheel in UI Config

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#92]
#### **Describe your issue**

I did a fresh install of my Rasp. Homebridge, I installed the Vieramatic plugin, when installed, I get the web ui config page but with a never ending spinning wheel. 

#### **Issue Context**

Please add the following items, when applicable:

- Homebridge 1.4.0
- Node.js Version | v16.13.2
- Npm Version | v8.3.1

Regular logs show's nothing.

![2022-01-24 16_18_06-Homebridge - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/64669806/150811207-91615415-43b0-4a3f-9207-07362e4b8ea3.png)

Tried on Chrome and Edge. 

I just restarted the whole Rasp, nothing's change. 

Here is the debug on Chrome : 

![2022-01-24 16_23_26-Settings](https://user-images.githubusercontent.com/64669806/150811598-c99ad6cf-3678-48ab-9a35-54d8687ad2c9.png)

I also tried on my iPhone on Safari, same result. 

Thanks for the help,

Best regards ,

Alexis

**Comment by Seexelas** [comment]
OK, so I used my backup of my config.json, get the part for my Panasonic Tv in the current config.json. restarted and there the web ui is working good.

**Comment by Seexelas** [comment]
Hi Antonio,

Thanks ;) Hope everything's good for you. 

I have the Panasonic 65GZ2000

**Comment by AntonioMeireles** [comment]
did you got anything relevant in the "Console" tab in Chromes's debug ?

**Comment by AntonioMeireles** [comment]
[will try to find a way to reproduce and will get back to you]

**Comment by Seexelas** [comment]
Not so far, it stays that way. 

Is there a discovery or something the first time ?

**Comment by AntonioMeireles** [comment]
there was. it's disabled - breaks docker setups. still looking at how to get it properly done for all. 
i suspect that  i 've got some regression - regarding clean installs / empty setups at 1st install. but need to try to repro when at home with some spare time.

**Comment by AntonioMeireles** [comment]
let's fix this specific issue 1st :-) then will bug you with docker ;-)

**Comment by AntonioMeireles** [comment]
@Seexelas 

confirm please that `homebridge-vieramatic@4.0.21` that i've just published fixes this issue.

**Comment by Seexelas** [comment]
Hi Antonio, 

I did a full uninstall, and a config.json cleanup. Rebooted my rasp, installed your plugin.

Same result, spinning wheel.

**Comment by AntonioMeireles** [comment]
@Seexelas 

thanks for reporting. That's unexpected. can you attach your 'cleaned' config.json ? also, what timezone are you on ?
(i'm only will be able to look at this again in around 11hrs)

**Comment by Seexelas** [comment]
You will find enclosed the config.json that is actually working (without your plugin as it is uninstalled).

I'm from Luxembourg, so I have right now 11:29 am.

Thanks for your help.

[Uploading config (1).txt…]()

**Comment by Seexelas** [comment]
[config (1).txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/7932745/config.1.txt)

**Comment by AntonioMeireles** [comment]
OK. will get back to you after yours' 9pm. **thanks**!

**Comment by AntonioMeireles** [comment]
@Seexelas  can you give a quick test to `homebridge-vieramatic@4.0.22` (went just out), please ?

**Comment by Seexelas** [comment]
Hi Antonio,

Still the same :S 

I switch to debut mode :S but nothing shows up

**Comment by AntonioMeireles** [comment]
@Seexelas 

plz install a debug version - npm i -g homebridge-vieramatic@debug, and restart homebridge.
then please attach here the contents from the "Console" tab in Chromes's debug - you should get lines starting by '(updateGlobalConfig) -->' there...

**Comment by Seexelas** [comment]
I have this : 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tvs')
    at J4 (VieraConfigUI.tsx:23:7)
    at async VieraConfigUI.tsx:70:24
J4 @ VieraConfigUI.tsx:23
await in J4 (async)
(anonymous) @ VieraConfigUI.tsx:70
n9 @ VieraConfigUI.tsx:67
i9 @ VieraConfigUI.tsx:69
p8 @ index.js:506
U2 @ index.js:173
l6 @ children.js:124
u8 @ index.js:392
U2 @ index.js:226
l6 @ children.js:124
U2 @ index.js:196
l6 @ children.js:124
U2 @ index.js:196
l6 @ children.js:124
U2 @ index.js:196
M @ render.js:16
R1 @ render.js:55
(anonymous) @ VieraConfigUI.tsx:335
_handleIncomingMessage @ ui.ts:70
postMessage (async)
confirmReady @ main-es2015.9d482d945810494ac85a.js:1
handleMessage @ main-es2015.9d482d945810494ac85a.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
onInvokeTask @ main-es2015.9d482d945810494ac85a.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
runTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
p @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
f @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
postMessage (async)
(anonymous) @ index.html?origin=http%3A%2F%2F192.168.1.250&v=4.0.22-debug1:17
load (async)
(anonymous) @ index.html?origin=http%3A%2F%2F192.168.1.250&v=4.0.22-debug1:16

**Comment by AntonioMeireles** [comment]
trying to understand **why** i do not get that error here...

**Comment by Seexelas** [comment]
I tried edge, chrome, safari on my phone and it's the same ! 

When I put the configuration of my tv back in config.json and restart. No more error in Chrome console and it works.

**Comment by Seexelas** [comment]
Hummm...

So with the web ui working, I switched to edit mode, delete my tv configuration, restarted and there it is working.

**Comment by AntonioMeireles** [comment]
this is bizarre. it works here (on the mac) on both firefox, safari, edge and chrome. and in safari in the iphone. 

<img width="999" alt="image" src="https://user-images.githubusercontent.com/743527/151058318-2b2706d8-8799-4d78-8a52-c89bac88087c.png">

**Comment by AntonioMeireles** [comment]
(wondering) did you did an hard refresh on the browser of the UI ? i suspect that perhaps the UI may had gone nuts between homebridge updates (as server (hb) side code changed but UI one not fully... (just thinking loud)

**Comment by Seexelas** [comment]
So this is weird... I took my Mac (M1 Chip). 

No issue on Safari, and Chrome. 

Safari IOS -> Nok 
Chrome, Edge Windows -> Nok 

I don't use Edge on my PC so it's like fresh. It's to become crazy.

**Comment by AntonioMeireles** [comment]
@Seexelas 

digging. thanks for your patience!

**Comment by Seexelas** [comment]
No problem, glad I can help

**Comment by AntonioMeireles** [comment]
@Seexelas  

install plz `npm i -g homebridge-vieramatic@4.0.22-debug3`. 

where is failed before still fails ? and where it works still works ?

**Comment by Seexelas** [comment]
Same results as before

**Comment by AntonioMeireles** [comment]
bah. thanks. will keep digging.

**Comment by Seexelas** [comment]
I need to go to sleep :) I'm sorry ! I'll continuy tomorrow

**Comment by AntonioMeireles** [comment]
@Seexelas 

(morning!) what IOS / safari version are you testing on ?

**Comment by Seexelas** [comment]
Morning :)

IOS 15.3 RC.

I will try with a fresh install of Chrome on my iPhone and let you know.

**Comment by AntonioMeireles** [comment]
humm... betas don't count :-) . OTOH that should go public this week or early next one. still digging.

**Comment by Seexelas** [comment]
So Chrome on IOS is working. 

Incognito mode on PC Chrome and Edge -> Working.

I tried removing my Adblock, but the same result.

**Comment by Seexelas** [comment]
Chrome / Edge normal mode
Safari IOS

**Comment by AntonioMeireles** [comment]
CFhrome / Edge work here in MacOS (plain Monterey) . can you try to disable / bissect extensions to see which one is b0rking things ?

**Comment by Seexelas** [comment]
I have an another PC with a fresh install. I will try on this one and let you know. Also same with the phone, I will try on my work phone.

**Comment by Seexelas** [comment]
Sooooooooooooooo...

Work phone (iOS 15.2.1) -> Safari ok
My other laptop (Windows 10) with Chrome and Adblock -> ok on Chrome. 

It's driving me crazy

**Comment by AntonioMeireles** [comment]
@Seexelas 

hi again! did you made any progresses on this ? here even with latest MacOS and IOS iterations (that went public last night) things keep behaving ... 

thanks in advance

**Comment by Seexelas** [comment]
Hi Antonio,

I did a lot of test, I don't know, I really don't know. 

I added my Tv manually for now, I don't know what to test more

**Comment by AntonioMeireles** [comment]
@Seexelas 

but are you still hitting the original issue or not ?

**Comment by Seexelas** [comment]
Yes.

Last results were : 

- MacOS (last update) -> Safari, Chrome OK 
- iOS Personnal -> 15.3 RC -> Nok Safari, Chrome ok 
- Work phone (iOS 15.2.1) -> Safari ok
- Work laptop -> Win11 -> Edge, Chrome -> Nok 
- Home laptop -> WIn10 -> Chrome, Edge ok

If I input my configuration into config.json, I don't have anymore issue with the webui (and if I delete the Tv Config by the plugin webui, after restart, it works). 

It's when I delete the whole plugin and configuration, than restart and the problem comes back.

**Comment by AntonioMeireles** [comment]
on your iPhone, when with spare time, check plz if issue remains after the update to 15.3 final.
still digging.  

and thanks again!

**Comment by Seexelas** [comment]
Hi Antonio.

I just did it, and it's the same.

**Comment by AntonioMeireles** [comment]
@Seexelas 

when you have time take a look at ` homebridge-vieramatic@4.0.23`. 

have a great weekend && thanks!

**Comment by Seexelas** [comment]
Hi Antonio,

Sadly it is still the same

thanks

**Comment by Seexelas** [comment]
Hi Antonio,

I saw that you put a new version, should I try it ? Or no corrections for my issue ? 

Many thanks

**Comment by AntonioMeireles** [comment]
> Hi Antonio,
> 
> I saw that you put a new version, should I try it ? Or no corrections for my issue ?
> 
> Many thanks

@Seexelas 

Hi again... 

given that i'm not 100% sure about what's going on, not sure... OTOH i'm hoping this is just a [esbuild](https://esbuild.github.io/) side effect and that somehow it will get fixed soon. (and yes esbuild was updated (albeit according to their [changelog](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md) the changes consumed in last version should - on paper - be immaterial to this particular issue.) 

have a great weekend!

**Comment by Seexelas** [comment]
Hi Antonio,

I needed to go back to my Docker Image for Homebridge due to some reasons. A did a clean install, and there it is working good on the first setup. 

I did a new rasp. setup, and now it is also working...

So case finally closed ^^ 

Thanks for the time and work.

Nice week end,

**Comment by AntonioMeireles** [comment]
@Seexelas hey again!


can you check by which version that happenned ? (probable culprit was really esbuild but it would be good to know what upstream fix did it for us :-) ) 


Thanks again!

**Comment by Nifc4life82** [comment]
I have the same issue could you please upload one of the older updates before the new interface think it’s pre 4.0  as this works with my old Panasonic tv but I updated and now nothing will work to connect it just get spinning cog tryed different browsers but still can’t get it to work

**Comment by AntonioMeireles** [comment]
@Nifc4life82 

sorry lag! (work/life not leaving much time left for watching TV or doing OSS development). 

can you provide more details about your setup (TV model, logs, etc) ?

@Seexelas things still work for you, right  ?

Thanks all for your patience && a great weekend !

**Comment by Seexelas** [comment]
Hi,

Yes no issues for me so far :)
